name: Papandayan Project Deployment Prod

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Check 'papandayancargo.id' service url
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: https://papandayancargo.id/
        max-attempts: 3
        retry-delay: 5s
    - name: Deploy to 'backend.papandayancargo.id'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PAPANDAYAN_BACKEND }}
        username: 'root'
        password: ${{ secrets.SSH_PASSWORD_PAPANDAYAN }}
        port: ${{ secrets.PORT_PAPANDAYAN }}
        script: |
          cd /var/www/html/backend.papandayancargo.id
          git checkout main
          git fetch
          git pull origin main
          php artisan optimize:clear
          cd /var/www/html
          chown -R papandayan:www-data backend.papandayancargo.id
          exit
    - name: Install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PAPANDAYAN_BACKEND }}
        username: 'papandayan'
        password: ${{ secrets.SSH_PASSWORD_PAPANDAYAN }}
        port: ${{ secrets.PORT_PAPANDAYAN }}
        script: |
          cd /var/www/html/backend.papandayancargo.id
          git checkout main
          composer install
          exit
    - name: Change permission
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PAPANDAYAN_BACKEND }}
        username: 'root'
        password: ${{ secrets.SSH_PASSWORD_PAPANDAYAN }}
        port: ${{ secrets.PORT_PAPANDAYAN }}
        script: |
          cd /var/www/html
          chown -R www-data:www-data backend.papandayancargo.id
          exit
    # - name: Install Dependencies
    #   run: composer install
